kind: Deployment
apiVersion: apps/v1
metadata:
  name: mursu-web
  namespace: default
spec:
  replicas: 1

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front
          image: "frontendimage"
          ports:
            - containerPort: 80
        - name: back
          image: "backendimage"
          ports:
            - containerPort: 5000
